handle initial addition of schema to the repo

diff --git a/schemachain b/schemachain
--- a/schemachain
+++ b/schemachain
@@ -30,43 +30,44 @@ function cmd_generate_migration() {
   
   CURRENT_SCHEMA_FINGERPRINT=$(fingerprint_schema $CURRENT_SCHEMA_FILE)
   
+  PREVIOUS_SCHEMA_FILE=/tmp/schema_previous.sql
+  if ! does_repo_have_commits || ! does_file_exist_in_history $CURRENT_SCHEMA_FILE; then
+    echo "No previous revisions of the schema found in the repo history."
+    echo "Will diff against an empty schema to produce the initial migration."
+    echo
+    
+    echo "" >$PREVIOUS_SCHEMA_FILE
+    PREVIOUS_SCHEMA_COMMIT=none
+    PREVIOUS_SCHEMA_FINGERPRINT=none
+  elif ! does_file_have_changes $CURRENT_SCHEMA_FILE; then
+    echo "Error: there are no uncommitted changes in $CURRENT_SCHEMA_FILE."
+    echo 
+    echo "Please run this tool before committing changes to the schema file,"
+    echo "then commit schema changes and migration together."
+    echo
+    exit 1    
+  else    
+    PREVIOUS_SCHEMA_COMMIT=$(git rev-list -1 HEAD $CURRENT_SCHEMA_FILE)
+    PREVIOUS_SCHEMA_FINGERPRINT=$(fingerprint_schema $PREVIOUS_SCHEMA_FILE)
+    git show ${PREVIOUS_SCHEMA_COMMIT}:${CURRENT_SCHEMA_FILE} >${PREVIOUS_SCHEMA_FILE}
+    
+    if [ "$CURRENT_SCHEMA_FINGERPRINT" = "$PREVIOUS_SCHEMA_FINGERPRINT" ]; then
+      echo "Error: Current schema and last committed schema are equivalent;"
+      echo "nothing to do."
+      echo
+      exit 1
+    fi
+  fi
+
   echo "Current schema:"
   echo "  - location: $CURRENT_SCHEMA_FILE"
   echo "  - fingerprint: $CURRENT_SCHEMA_FINGERPRINT"
   echo
 
-  if ! does_file_have_changes $CURRENT_SCHEMA_FILE; then
-    echo "Error: current schema has no uncommitted changes; nothing to do."
-    echo 
-    echo "Please run this tool before committing changes to the schema file,"
-    echo "then commit schema changes and generated migration together."
-    echo
-    exit 1
-  fi
-  
-  PREVIOUS_SCHEMA_FILE=/tmp/schema_previous.sql
-
-  if is_file_in_repo $CURRENT_SCHEMA_FILE; then
-    git show ${PREVIOUS_SCHEMA_COMMIT}:${CURRENT_SCHEMA_FILE} >${PREVIOUS_SCHEMA_FILE}
-    PREVIOUS_SCHEMA_COMMIT=$(git rev-list -1 HEAD $CURRENT_SCHEMA_FILE)
-    PREVIOUS_SCHEMA_FINGERPRINT=$(fingerprint_schema $PREVIOUS_SCHEMA_FILE)
-  else
-    echo >$PREVIOUS_SCHEMA_FILE
-    PREVIOUS_SCHEMA_COMMIT=none
-    PREVIOUS_SCHEMA_FINGERPRINT=none
-  fi
-
-  echo "Last committed schema:"
-  echo "  - location: ${CURRENT_SCHEMA_FILE}@${PREVIOUS_SCHEMA_COMMIT}"
+  echo "Previous schema:"
+  echo "  - commit: ${PREVIOUS_SCHEMA_COMMIT}"
   echo "  - fingerprint: ${PREVIOUS_SCHEMA_FINGERPRINT}"
   echo
-
-  if [ "$CURRENT_SCHEMA_FINGERPRINT" = "$PREVIOUS_SCHEMA_FINGERPRINT" ]; then
-    echo "Error: Current schema and last committed schema are equivalent."
-    echo "Nothing to do."
-    echo
-    exit 1
-  fi
   
   ######################################################################
 
@@ -96,7 +97,7 @@ function cmd_generate_migration() {
   ######################################################################
 
   MIGRATION_FILE=migrations/from_${PREVIOUS_SCHEMA_FINGERPRINT}_to_${CURRENT_SCHEMA_FINGERPRINT}.sql
-  echo -n "Diff'ing previous and current schema... "
+  echo -n "Diff'ing previous and current schemas... "
   # XXX why does migra exit with status code 2?
   docker run --net host migra:local migra --unsafe \
          "${DB_PREVIOUS_URI}" "${DB_CURRENT_URI}" >${MIGRATION_FILE} || true
@@ -171,7 +172,11 @@ function does_file_have_changes() {
   fi
 }
 
-function is_file_in_repo() {
+function does_repo_have_commits() {
+  test "$(git rev-parse HEAD 2>/dev/null)" != "HEAD"
+}
+
+function does_file_exist_in_history() {
   local FILE=$1
   git ls-files --error-unmatch $CURRENT_SCHEMA_FILE >/dev/null 2>&1
 }
